"use client";

import * as React from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BookOpen, Binary, ShieldAlert, GraduationCap, User2, RefreshCw, Cpu, Award, Sparkles, ExternalLink, Code } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";
import { motion } from "framer-motion";

// List of physics formulas for the Daily Formula Widget
const formulas = [
  {
    latex: "i\\hbar \\frac{\\partial}{\\partial t}\\Psi = \\hat{H}\\Psi",
    name: "Schrödinger Equation",
    desc: "The fundamental equation of quantum mechanics, describing how the quantum state of a physical system changes with time.",
  },
  {
    latex: "G_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}",
    name: "Einstein Field Equations",
    desc: "The core of General Relativity, relating the geometry of spacetime to the distribution of matter and energy within it.",
  },
  {
    latex: "\\nabla \\times \\mathbf{B} = \\mu_0\\mathbf{J} + \\mu_0\\epsilon_0\\frac{\\partial\\mathbf{E}}{\\partial t}",
    name: "Ampère-Maxwell Law",
    desc: "Part of Maxwell's equations, showing that magnetic fields are generated by electric currents and changing electric fields.",
  },
  {
    latex: "S = k_B \\ln \\Omega",
    name: "Boltzmann Entropy Formula",
    desc: "The bridge between thermodynamics and statistical mechanics, relating entropy (S) to the number of microstates (Ω).",
  },
  {
    latex: "\\Delta x \\cdot \\Delta p \\ge \\frac{\\hbar}{2}",
    name: "Heisenberg Uncertainty Principle",
    desc: "Stating a fundamental limit to the precision with which certain pairs of physical properties of a particle can be known.",
  },
];

export default function Home() {
  const [formulaIndex, setFormulaIndex] = React.useState(0);
  const canvasRef = React.useRef<HTMLCanvasElement>(null);

  // Interactive Physics Sandbox Canvas
  React.useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;

    let animationFrameId: number;
    let width = (canvas.width = canvas.offsetWidth);
    let height = (canvas.height = canvas.offsetHeight);

    interface PhysicsBall {
      x: number;
      y: number;
      vx: number;
      vy: number;
      radius: number;
      color: string;
      label: string;
      isDragging: boolean;
    }

    const balls: PhysicsBall[] = [
      { x: width * 0.25, y: height * 0.4, vx: 2, vy: 0, radius: 24, color: "#6366f1", label: "Ψ", isDragging: false },
      { x: width * 0.5, y: height * 0.3, vx: -1.5, vy: 1, radius: 28, color: "#10b981", label: "c", isDragging: false },
      { x: width * 0.75, y: height * 0.5, vx: 1, vy: -2, radius: 26, color: "#f59e0b", label: "ħ", isDragging: false },
    ];

    const gravity = 0.2;
    const friction = 0.98;
    const bounce = 0.7;
    let activeDragBall: PhysicsBall | null = null;
    let mouse = { x: 0, y: 0 };

    const handleResize = () => {
      if (!canvas) return;
      width = canvas.width = canvas.offsetWidth;
      height = canvas.height = canvas.offsetHeight;
    };
    window.addEventListener("resize", handleResize);

    const getMousePos = (e: MouseEvent | TouchEvent) => {
      const rect = canvas.getBoundingClientRect();
      const clientX = "touches" in e ? e.touches[0].clientX : e.clientX;
      const clientY = "touches" in e ? e.touches[0].clientY : e.clientY;
      return {
        x: clientX - rect.left,
        y: clientY - rect.top,
      };
    };

    const onMouseDown = (e: MouseEvent | TouchEvent) => {
      const pos = getMousePos(e);
      mouse = pos;
      for (const ball of balls) {
        const dx = ball.x - pos.x;
        const dy = ball.y - pos.y;
        if (Math.sqrt(dx * dx + dy * dy) < ball.radius) {
          ball.isDragging = true;
          activeDragBall = ball;
          break;
        }
      }
    };

    const onMouseMove = (e: MouseEvent | TouchEvent) => {
      const pos = getMousePos(e);
      if (activeDragBall) {
        activeDragBall.vx = (pos.x - activeDragBall.x) * 0.2;
        activeDragBall.vy = (pos.y - activeDragBall.y) * 0.2;
        activeDragBall.x = pos.x;
        activeDragBall.y = pos.y;
      }
      mouse = pos;
    };

    const onMouseUp = () => {
      if (activeDragBall) {
        activeDragBall.isDragging = false;
        activeDragBall = null;
      }
    };

    canvas.addEventListener("mousedown", onMouseDown);
    canvas.addEventListener("mousemove", onMouseMove);
    canvas.addEventListener("touchstart", onMouseDown);
    canvas.addEventListener("touchmove", onMouseMove);
    window.addEventListener("mouseup", onMouseUp);
    window.addEventListener("touchend", onMouseUp);

    const updatePhysics = () => {
      ctx.clearRect(0, 0, width, height);

      balls.forEach((ball, idx) => {
        if (!ball.isDragging) {
          ball.vy += gravity;
          ball.vx *= friction;
          ball.vy *= friction;

          ball.x += ball.vx;
          ball.y += ball.vy;

          if (ball.x + ball.radius > width) {
            ball.x = width - ball.radius;
            ball.vx = -ball.vx * bounce;
          } else if (ball.x - ball.radius < 0) {
            ball.x = 0 + ball.radius;
            ball.vx = -ball.vx * bounce;
          }

          if (ball.y + ball.radius > height) {
            ball.y = height - ball.radius;
            ball.vy = -ball.vy * bounce;
            ball.vx *= 0.95;
          }
        }

        ctx.beginPath();
        ctx.arc(ball.x, ball.y + 2, ball.radius, 0, Math.PI * 2);
        ctx.fillStyle = "rgba(0, 0, 0, 0.15)";
        ctx.fill();

        ctx.beginPath();
        ctx.arc(ball.x, ball.y, ball.radius, 0, Math.PI * 2);
        ctx.fillStyle = ball.color;
        ctx.fill();

        ctx.fillStyle = "#ffffff";
        ctx.font = "bold 16px sans-serif";
        ctx.textAlign = "center";
        ctx.textBaseline = "middle";
        ctx.fillText(ball.label, ball.x, ball.y);
      });

      animationFrameId = requestAnimationFrame(updatePhysics);
    };

    updatePhysics();

    return () => {
      window.removeEventListener("resize", handleResize);
      if (canvas) {
        canvas.removeEventListener("mousedown", onMouseDown);
        canvas.removeEventListener("mousemove", onMouseMove);
      }
      window.removeEventListener("mouseup", onMouseUp);
      cancelAnimationFrame(animationFrameId);
    };
  }, []);

  const cycleFormula = () => {
    setFormulaIndex((prev) => (prev + 1) % formulas.length);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-10 flex flex-col gap-10">
        
        {/* Hero Section */}
        <section className="flex flex-col md:flex-row items-center justify-between gap-8 py-8 md:py-12 border-b border-border">
          <div className="flex-1 flex flex-col gap-4 text-center md:text-left">
            <div className="inline-flex self-center md:self-start items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-500 border border-indigo-500/20">
              <Award className="size-3.5" />
              <span>Sharif University of Technology</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground via-foreground to-indigo-500 leading-none">
              Abulfadl Ahmadi
            </h1>
            <h2 className="text-xl md:text-2xl font-mono text-muted-foreground">
              Physics Student & Full-Stack Developer
            </h2>
            <p className="max-w-xl text-muted-foreground text-md leading-relaxed">
              Passionate about using coding skills for physics projects, numerical simulations, network tunneling protocols (Hyper-Tunnel, DS-tunnel), and open-source contributions.
            </p>
            <div className="flex flex-wrap items-center justify-center md:justify-start gap-3 mt-2">
              <Link href="/about" className={cn(buttonVariants({ variant: "default" }), "group h-10 px-5 active:scale-97 transition-transform")}>
                Explore CV <ArrowRight className="size-4 group-hover:translate-x-0.5 transition-transform ml-1" />
              </Link>
              <Link href="/projects" className={cn(buttonVariants({ variant: "outline" }), "h-10 px-5 active:scale-97 transition-transform")}>
                View Projects
              </Link>
            </div>
          </div>
          
          {/* Avatar Profile Card */}
          <div className="relative size-64 md:size-72 flex items-center justify-center rounded-3xl p-2 bg-gradient-to-br from-indigo-500/20 to-emerald-500/20 border border-border shadow-xl overflow-hidden">
            <div className="relative w-full h-full rounded-2xl overflow-hidden border border-border/50">
              <Image
                src="https://avatars.githubusercontent.com/u/88237116?v=4"
                alt="Abulfadl Ahmadi Profile Picture"
                fill
                className="object-cover"
                unoptimized
              />
            </div>
          </div>
        </section>

        {/* Bento Grid Showcase */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Bento Card 1: Interactive Physics Sandbox */}
          <div className="md:col-span-2 rounded-2xl border border-border bg-card/40 p-6 flex flex-col gap-4 relative overflow-hidden shadow-sm">
            <div className="flex items-center justify-between z-10">
              <div className="flex items-center gap-2">
                <Cpu className="size-5 text-indigo-500" />
                <h3 className="font-bold text-md">Physics Canvas Sandbox</h3>
              </div>
              <span className="text-[10px] font-mono bg-indigo-500/10 text-indigo-500 px-2 py-0.5 rounded border border-indigo-500/20">
                Interactive Drag & Collision
              </span>
            </div>
            <p className="text-xs text-muted-foreground z-10 max-w-md">
              Drag and toss the physics spheres below. They collide with momentum and bounce off boundaries using 2D rigid-body vector kinetics.
            </p>

            <div className="w-full h-56 rounded-xl bg-black/5 dark:bg-black/40 border border-border relative overflow-hidden">
              <canvas ref={canvasRef} className="w-full h-full block cursor-grab active:cursor-grabbing" />
            </div>
          </div>

          {/* Bento Card 2: Daily Formula Widget */}
          <div className="rounded-2xl border border-border bg-card/40 p-6 flex flex-col justify-between gap-4 shadow-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <BookOpen className="size-5 text-emerald-500" />
                <h3 className="font-bold text-md">Formula Spotlight</h3>
              </div>
              <Button
                variant="ghost"
                size="icon-sm"
                onClick={cycleFormula}
                className="hover:rotate-180 transition-transform duration-300"
                title="Cycle Formula"
              >
                <RefreshCw className="size-3.5" />
              </Button>
            </div>

            <div className="flex flex-col gap-3 py-4">
              <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-center font-mono text-sm text-indigo-600 dark:text-indigo-400 font-bold overflow-x-auto">
                {`$$ ${formulas[formulaIndex].latex} $$`}
              </div>
              <div className="font-semibold text-sm">{formulas[formulaIndex].name}</div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {formulas[formulaIndex].desc}
              </p>
            </div>

            <Link href="/notes" className="text-xs font-mono text-indigo-500 flex items-center justify-between border-t border-border/50 pt-3 hover:underline">
              <span>Read Physics Notes</span>
              <ArrowRight className="size-3.5" />
            </Link>
          </div>

          {/* Bento Card 3: Pinned Repositories Spotlight */}
          <div className="md:col-span-3 rounded-2xl border border-border bg-card/40 p-6 flex flex-col gap-6 shadow-sm">
            <div className="flex items-center justify-between border-b border-border/50 pb-3">
              <div className="flex items-center gap-2">
                <Code className="size-5 text-indigo-500" />
                <h3 className="font-bold text-md">Featured GitHub Repositories</h3>
              </div>
              <a href="https://github.com/Abulfadl-Ahmadi" target="_blank" rel="noopener noreferrer" className="text-xs font-mono text-indigo-500 hover:underline flex items-center gap-1">
                @Abulfadl-Ahmadi <ExternalLink className="size-3" />
              </a>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {/* Repo 1 */}
              <a href="https://github.com/Abulfadl-Ahmadi/Hyper-Tunnel" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Hyper-Tunnel</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">Asymmetric transport layer combining DNS upstream tunneling with packet delivery.</p>
                </div>
                <span className="text-[10px] font-mono text-sky-500">Go</span>
              </a>

              {/* Repo 2 */}
              <a href="https://github.com/Abulfadl-Ahmadi/DS-tunnel" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">DS-tunnel</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">DNS resolving and IP spoofing payload tunnel in Go.</p>
                </div>
                <span className="text-[10px] font-mono text-sky-500">Go</span>
              </a>

              {/* Repo 3 */}
              <a href="https://github.com/Abulfadl-Ahmadi/Academia" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Academia</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">Online learning hub powered by DRF and Vite for high school students.</p>
                </div>
                <span className="text-[10px] font-mono text-blue-500">TypeScript</span>
              </a>

              {/* Repo 4 */}
              <a href="https://github.com/Abulfadl-Ahmadi/Online-Shop" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Online-Shop</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">E-commerce store platform powered by Django backend.</p>
                </div>
                <span className="text-[10px] font-mono text-amber-500">Python / Django</span>
              </a>
            </div>
          </div>

        </section>

      </main>

      <footer className="border-t border-border bg-card/20 py-6 mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-muted-foreground font-mono">
          <div>© {new Date().getFullYear()} Abulfadl Ahmadi. Sharif University of Technology.</div>
          <div className="flex items-center gap-4">
            <Link href="/about" className="hover:text-foreground">About CV</Link>
            <span>•</span>
            <Link href="/projects" className="hover:text-foreground">Projects</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
