"use client";

import * as React from "react";
import Link from "next/link";
import Image from "next/image";
import { ArrowRight, BookOpen, RefreshCw, Award, Sparkles, ExternalLink, Code } from "lucide-react";
import { Button, buttonVariants } from "@/components/ui/button";
import { Header } from "@/components/header";
import { cn } from "@/lib/utils";

// List of physics formulas for the Daily Formula Widget
const formulas = [
  {
    latex: "i\\hbar \\frac{\\partial}{\\partial t}\\Psi = \\hat{H}\\Psi",
    name: "Schrödinger Equation",
    desc: "The fundamental equation of quantum mechanics, describing how the quantum state of a physical system changes with time.",
  },
  {
    latex: "G_{\\mu\\nu} + \\Lambda g_{\\mu\\nu} = \\frac{8\\pi G}{c^4} T_{\\mu\\nu}",
    name: "Einstein Field Equations",
    desc: "The core of General Relativity, relating the geometry of spacetime to the distribution of matter and energy within it.",
  },
  {
    latex: "\\nabla \\times \\mathbf{B} = \\mu_0\\mathbf{J} + \\mu_0\\epsilon_0\\frac{\\partial\\mathbf{E}}{\\partial t}",
    name: "Ampère-Maxwell Law",
    desc: "Part of Maxwell's equations, showing that magnetic fields are generated by electric currents and changing electric fields.",
  },
  {
    latex: "S = k_B \\ln \\Omega",
    name: "Boltzmann Entropy Formula",
    desc: "The bridge between thermodynamics and statistical mechanics, relating entropy (S) to the number of microstates (Ω).",
  },
  {
    latex: "\\Delta x \\cdot \\Delta p \\ge \\frac{\\hbar}{2}",
    name: "Heisenberg Uncertainty Principle",
    desc: "Stating a fundamental limit to the precision with which certain pairs of physical properties of a particle can be known.",
  },
];

export default function Home() {
  const [formulaIndex, setFormulaIndex] = React.useState(0);

  const cycleFormula = () => {
    setFormulaIndex((prev) => (prev + 1) % formulas.length);
  };

  return (
    <div className="flex flex-col min-h-screen">
      <Header />

      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-10 flex flex-col gap-10">
        
        {/* Hero Section */}
        <section className="flex flex-col md:flex-row items-center justify-between gap-8 py-8 md:py-12 border-b border-border">
          <div className="flex-1 flex flex-col gap-4 text-center md:text-left">
            <div className="inline-flex self-center md:self-start items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-500/10 text-indigo-500 border border-indigo-500/20">
              <Award className="size-3.5" />
              <span>Sharif University of Technology</span>
            </div>
            <h1 className="text-4xl md:text-6xl font-extrabold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground via-foreground to-indigo-500 leading-none">
              Abulfadl Ahmadi
            </h1>
            <h2 className="text-xl md:text-2xl font-mono text-muted-foreground">
              Physics Student & Full-Stack Developer
            </h2>
            <p className="max-w-xl text-muted-foreground text-md leading-relaxed">
              Passionate about using coding skills for physics projects, numerical simulations, network tunneling protocols (Hyper-Tunnel, DS-tunnel), and open-source contributions.
            </p>
            <div className="flex flex-wrap items-center justify-center md:justify-start gap-3 mt-2">
              <Link href="/about" className={cn(buttonVariants({ variant: "default" }), "group h-10 px-5 active:scale-97 transition-transform")}>
                Explore CV <ArrowRight className="size-4 group-hover:translate-x-0.5 transition-transform ml-1" />
              </Link>
              <Link href="/projects" className={cn(buttonVariants({ variant: "outline" }), "h-10 px-5 active:scale-97 transition-transform")}>
                View Projects
              </Link>
            </div>
          </div>
          
          {/* Avatar Profile Card */}
          <div className="relative size-64 md:size-72 flex items-center justify-center rounded-3xl p-2 bg-gradient-to-br from-indigo-500/20 to-emerald-500/20 border border-border shadow-xl overflow-hidden">
            <div className="relative w-full h-full rounded-2xl overflow-hidden border border-border/50">
              <Image
                src="https://avatars.githubusercontent.com/u/88237116?v=4"
                alt="Abulfadl Ahmadi Profile Picture"
                fill
                className="object-cover"
                unoptimized
              />
            </div>
          </div>
        </section>

        {/* Bento Grid Showcase */}
        <section className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          {/* Bento Card 1: Stats Overview */}
          <div className="md:col-span-2 rounded-2xl border border-border bg-card/40 p-6 flex flex-col gap-4 shadow-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Code className="size-5 text-indigo-500" />
                <h3 className="font-bold text-md">Development Overview</h3>
              </div>
              <span className="text-[10px] font-mono bg-indigo-500/10 text-indigo-500 px-2 py-0.5 rounded border border-indigo-500/20">
                Open Source
              </span>
            </div>
            <div className="grid grid-cols-3 gap-4 mt-2">
              <div className="flex flex-col gap-1">
                <span className="text-3xl font-extrabold text-indigo-500">30+</span>
                <span className="text-xs text-muted-foreground font-mono">Repositories</span>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-3xl font-extrabold text-emerald-500">5</span>
                <span className="text-xs text-muted-foreground font-mono">Languages</span>
              </div>
              <div className="flex flex-col gap-1">
                <span className="text-3xl font-extrabold text-amber-500">4+</span>
                <span className="text-xs text-muted-foreground font-mono">Years Active</span>
              </div>
            </div>
            <p className="text-xs text-muted-foreground max-w-md leading-relaxed mt-2">
              From Go network tunneling protocols to full-stack educational platforms and physics lab reports — explore the full range of projects on GitHub.
            </p>
            <Link href="/projects" className="text-xs font-mono text-indigo-500 flex items-center gap-1 hover:underline mt-1">
              Browse all projects <ArrowRight className="size-3.5" />
            </Link>
          </div>

          {/* Bento Card 2: Daily Formula Widget */}
          <div className="rounded-2xl border border-border bg-card/40 p-6 flex flex-col justify-between gap-4 shadow-sm">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <BookOpen className="size-5 text-emerald-500" />
                <h3 className="font-bold text-md">Formula Spotlight</h3>
              </div>
              <Button
                variant="ghost"
                size="icon-sm"
                onClick={cycleFormula}
                className="hover:rotate-180 transition-transform duration-300"
                title="Cycle Formula"
              >
                <RefreshCw className="size-3.5" />
              </Button>
            </div>

            <div className="flex flex-col gap-3 py-4">
              <div className="p-4 rounded-xl bg-indigo-500/10 border border-indigo-500/20 text-center font-mono text-sm text-indigo-600 dark:text-indigo-400 font-bold overflow-x-auto">
                {`$$ ${formulas[formulaIndex].latex} $$`}
              </div>
              <div className="font-semibold text-sm">{formulas[formulaIndex].name}</div>
              <p className="text-xs text-muted-foreground leading-relaxed">
                {formulas[formulaIndex].desc}
              </p>
            </div>

            <Link href="/notes" className="text-xs font-mono text-indigo-500 flex items-center justify-between border-t border-border/50 pt-3 hover:underline">
              <span>Read Physics Notes</span>
              <ArrowRight className="size-3.5" />
            </Link>
          </div>

          {/* Bento Card 3: Pinned Repositories Spotlight */}
          <div className="md:col-span-3 rounded-2xl border border-border bg-card/40 p-6 flex flex-col gap-6 shadow-sm">
            <div className="flex items-center justify-between border-b border-border/50 pb-3">
              <div className="flex items-center gap-2">
                <Code className="size-5 text-indigo-500" />
                <h3 className="font-bold text-md">Featured GitHub Repositories</h3>
              </div>
              <a href="https://github.com/Abulfadl-Ahmadi" target="_blank" rel="noopener noreferrer" className="text-xs font-mono text-indigo-500 hover:underline flex items-center gap-1">
                @Abulfadl-Ahmadi <ExternalLink className="size-3" />
              </a>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
              {/* Repo 1 */}
              <a href="https://github.com/Abulfadl-Ahmadi/Hyper-Tunnel" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Hyper-Tunnel</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">High-performance asymmetric transport layer combining DNS upstream tunneling with IP spoofing downstream delivery.</p>
                </div>
                <span className="text-[10px] font-mono text-sky-500">Go</span>
              </a>

              {/* Repo 2 */}
              <a href="https://github.com/Abulfadl-Ahmadi/spoof-tunnel" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Spoof Tunnel</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">Layer 3/4 tunneling proxy bypassing DPI via mutual bidirectional IP spoofing.</p>
                </div>
                <span className="text-[10px] font-mono text-sky-500">Go</span>
              </a>

              {/* Repo 3 */}
              <a href="https://github.com/Abulfadl-Ahmadi/Academia" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Academia</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">Educational platform with DRF backend, React 19 frontend, SMS auth, test management, and AI integration.</p>
                </div>
                <span className="text-[10px] font-mono text-blue-500">TypeScript / Python</span>
              </a>

              {/* Repo 4 */}
              <a href="https://github.com/Abulfadl-Ahmadi/physics_lab4" target="_blank" rel="noopener noreferrer" className="p-4 rounded-xl border border-border bg-muted/20 hover:border-indigo-500/40 transition-colors flex flex-col justify-between gap-3 group">
                <div>
                  <div className="text-sm font-bold group-hover:text-indigo-500 transition-colors">Physics Lab IV</div>
                  <p className="text-xs text-muted-foreground mt-1 line-clamp-2">10 modern physics lab experiments: Franck-Hertz, Photoelectric Effect, Electron Diffraction, and more.</p>
                </div>
                <span className="text-[10px] font-mono text-emerald-500">TeX / Python</span>
              </a>
            </div>
          </div>

        </section>

      </main>

      <footer className="border-t border-border bg-card/20 py-6 mt-12">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 flex flex-col md:flex-row items-center justify-between gap-4 text-xs text-muted-foreground font-mono">
          <div>© {new Date().getFullYear()} Abulfadl Ahmadi. Sharif University of Technology.</div>
          <div className="flex items-center gap-4">
            <Link href="/about" className="hover:text-foreground">About CV</Link>
            <span>•</span>
            <Link href="/projects" className="hover:text-foreground">Projects</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
